# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPIP <- function(seeds, scans, mzs, clu, mztol, gap) {
    .Call('_KPICutils_getPIP', PACKAGE = 'KPICutils', seeds, scans, mzs, clu, mztol, gap)
}

waveft <- function(omega, scales) {
    .Call('_KPICutils_waveft', PACKAGE = 'KPICutils', omega, scales)
}

cwtft <- function(val) {
    .Call('_KPICutils_cwtft', PACKAGE = 'KPICutils', val)
}

localMax <- function(cwt2d) {
    .Call('_KPICutils_localMax', PACKAGE = 'KPICutils', cwt2d)
}

localMin <- function(cwt2d) {
    .Call('_KPICutils_localMin', PACKAGE = 'KPICutils', cwt2d)
}

ridgesDetection <- function(cwt2d, val) {
    .Call('_KPICutils_ridgesDetection', PACKAGE = 'KPICutils', cwt2d, val)
}

peaksPosition <- function(val, ridges, cwt2d) {
    .Call('_KPICutils_peaksPosition', PACKAGE = 'KPICutils', val, ridges, cwt2d)
}

getSignal <- function(cwt2d, ridges, peaks) {
    .Call('_KPICutils_getSignal', PACKAGE = 'KPICutils', cwt2d, ridges, peaks)
}

